### ISSUE TITLE
Prof, l’esercizio richiede la stampa di colonne alterne a 2 a 2 intervallate da uno spazio; credo abbia postato un altro esercizio.

### ISSUE THREAD

**Issue by kevinm6** [Dexterux/LaboratorioProgrammazione2020#1]
https://github.com/Dexterux/LaboratorioProgrammazione2020/blob/58fd7b395c2f1abf7ec60b145247986e745fd934/Laboratorio_3/Cicli_annidati/esercizio_11/quadrato_colonne_alterne_2.go#L13

**Comment by Dexterux** [comment]
Sì, il codice corrispondeva ad un esercizio più complesso. 
Corretto e caricato il codice corrispondente 77ec91a914dffac284cf496029f634e01a9fa32b.
